.libPaths('~/R/library')
library(GenomicRanges)
setwd('/data/home/bt25018/sma_epigenomics_pipeline')
cache <- readRDS('results/dmr/meth_pooled_cache.rds')
cat('Conditions:', paste(names(cache), collapse=', '), '\n')
chrs <- table(as.character(seqnames(cache[[1]])))
cat('Chromosomes present:\n')
print(chrs[chrs > 0])
cat('Total CpGs:', length(cache[[1]]), '\n')
